[WIP] Integer Only Common Operations
purpleprotocol/purple_prototype pull request #141
Opened 2019-10-02 22:51 UTC by iNemesis21

Hello.
This PR closes #100

2019-10-03 13:19 UTC, octavonce requested changes
Hi there!

This looks great, with only a few pointers left in the review.

2019-10-03 13:19 UTC, octavonce commented on src/purple_vm/src/primitives/value.rs
> +    }
Could you please add match clauses for arrays up to 256 items?

2019-10-03 13:19 UTC, octavonce commented on src/purple_vm/src/primitives/value.rs
> +    }
Please add match clauses for arrays up to 256 items in length.

2019-10-03 13:19 UTC, octavonce commented on src/purple_vm/src/primitives/value.rs
> +}
Please add match clauses for arrays up to 256 items in length

2019-10-03 13:19 UTC, octavonce commented on src/purple_vm/src/primitives/value.rs
> +}
Please add match clauses for arrays up to 256 items in length

2019-10-03 13:19 UTC, octavonce commented on src/purple_vm/src/primitives/value.rs
> +}
Please add match clauses for arrays up to 256 items in length.

2019-10-03 13:19 UTC, octavonce commented on src/purple_vm/src/primitives/value.rs
> +}
Please add match clauses for arrays up to 256 items in length.

2019-10-10 21:13 UTC, iNemesis21 commented
Hi @octavonce,
I've finished the implementation for this PR and I've handled issue #143 also.
Since the const-generics feature of rust is not stable yet, for arrays larger than 32 I've made conversions to vecs, but I left a TODO so when the feature is available and stable, we should get rid of the conversions.

2019-10-10 22:18 UTC, octavonce commented
@iNemesis21 That's good enough for now. I'm going to merge this as is. Could you also please open an issue about getting rid of `to_vec()`s so it will be documented?

2019-10-10 22:19 UTC, octavonce approved these changes

2019-10-10 22:19 UTC, merged