[WIP] Mempool - Prune logic
purpleprotocol/purple_prototype pull request #286
Opened 2020-05-06 21:22 UTC by iNemesis21

Hello,
This PR closes #171.

2020-05-22 06:17 UTC, iNemesis21 commented
Hi @octavonce 
The implementation is done.
The recalculation of the transaction sets will be done in a separate PR. I will open an issue for this.

2020-05-22 13:29 UTC, octavonce requested changes
@iNemesis21 Great work so far! However, I would like to propose a few modifications to this PR before merging:
* Currently, transactions prune priority is based primarily on the timestamp i.e. oldest will be removed first. This is wrong since miners prioritise appending transactions to blocks by fee primarily and then the time added to the mempool **i.e. choose transactions with the highest fees and append them to the block in ascending order based on the time they were created**. If the mempool overflows during a short burst, good transactions might be deleted.
* To solve the above problem we can introduce a configurable transaction expiry time. A transaction is considered "expired" after a threshold time has passed i.e. from a minimum of 10 seconds to infinity. "Expired" Transactions will be pruned first.
* Another thing to consider is transaction propagation. Have we propagated a specific transaction? That can be removed before one that isn't propagated. SPV nodes will have a small mempool so they can remove propagated transactions, even if they are good, in order to save resources. Miner nodes on the other hand want a very big mempool with custom transaction expiry times and conditions. The mempool needs to be able to handle all of these cases.
* One other small change which should go in this PR as well is the ability for the user to pass the prune threshold as parameter via a given flag.

Let me know your thoughts. Also, please rebase your branch and check the output of `cargo clippy` so the CI checks will pass.

2020-06-01 17:24 UTC, octavonce requested changes

2020-06-01 17:24 UTC, octavonce commented on src/mempool/src/mempool.rs
> -    pub fn exists(&self, tx_hash: &ShortHash) -> bool {
This was good before. It's better to pass pointers as parameters unless the functionality requires the structure to be consumed.

2020-06-01 17:28 UTC, octavonce submitted a review, later dismissed

2020-06-01 17:49 UTC, octavonce approved these changes

2020-06-01 18:01 UTC, merged